# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import docker_manager_pb2 as docker__manager__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in docker_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DockerManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListContainers = channel.unary_unary(
                '/DockerManager/ListContainers',
                request_serializer=docker__manager__pb2.Empty.SerializeToString,
                response_deserializer=docker__manager__pb2.ContainerList.FromString,
                _registered_method=True)
        self.StartContainer = channel.unary_unary(
                '/DockerManager/StartContainer',
                request_serializer=docker__manager__pb2.ContainerRequest.SerializeToString,
                response_deserializer=docker__manager__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.StopContainer = channel.unary_unary(
                '/DockerManager/StopContainer',
                request_serializer=docker__manager__pb2.ContainerRequest.SerializeToString,
                response_deserializer=docker__manager__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ListImages = channel.unary_unary(
                '/DockerManager/ListImages',
                request_serializer=docker__manager__pb2.Empty.SerializeToString,
                response_deserializer=docker__manager__pb2.ImageList.FromString,
                _registered_method=True)


class DockerManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListContainers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DockerManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContainers,
                    request_deserializer=docker__manager__pb2.Empty.FromString,
                    response_serializer=docker__manager__pb2.ContainerList.SerializeToString,
            ),
            'StartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartContainer,
                    request_deserializer=docker__manager__pb2.ContainerRequest.FromString,
                    response_serializer=docker__manager__pb2.ActionResponse.SerializeToString,
            ),
            'StopContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopContainer,
                    request_deserializer=docker__manager__pb2.ContainerRequest.FromString,
                    response_serializer=docker__manager__pb2.ActionResponse.SerializeToString,
            ),
            'ListImages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListImages,
                    request_deserializer=docker__manager__pb2.Empty.FromString,
                    response_serializer=docker__manager__pb2.ImageList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DockerManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DockerManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DockerManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DockerManager/ListContainers',
            docker__manager__pb2.Empty.SerializeToString,
            docker__manager__pb2.ContainerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DockerManager/StartContainer',
            docker__manager__pb2.ContainerRequest.SerializeToString,
            docker__manager__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DockerManager/StopContainer',
            docker__manager__pb2.ContainerRequest.SerializeToString,
            docker__manager__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DockerManager/ListImages',
            docker__manager__pb2.Empty.SerializeToString,
            docker__manager__pb2.ImageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
